export {
  createCompany,
  getCompanyById,
  getCompanyByIdIncludingDeleted,
  listCompanies,
  updateCompany,
  softDeleteCompany,
  type Company,
  type CreateCompanyInput,
  type UpdateCompanyInput,
  type ListCompaniesInput,
} from "./companies";
export {
  createContact,
  getContactById,
  getContactByIdIncludingDeleted,
  getContactByEmail,
  listContacts,
  updateContact,
  softDeleteContact,
  type Contact,
  type CreateContactInput,
  type UpdateContactInput,
  type ListContactsInput,
} from "./contacts";
export {
  createPipeline,
  getPipelineById,
  getPipelineByIdIncludingDeleted,
  listPipelines,
  updatePipeline,
  setDefaultPipeline,
  softDeletePipeline,
  type Pipeline,
  type CreatePipelineInput,
  type UpdatePipelineInput,
  type ListPipelinesInput,
} from "./pipelines";
export {
  createPipelineStage,
  getPipelineStageById,
  getPipelineStageByIdIncludingDeleted,
  listPipelineStages,
  updatePipelineStage,
  softDeletePipelineStage,
  type PipelineStage,
  type CreatePipelineStageInput,
  type UpdatePipelineStageInput,
} from "./pipeline-stages";
export {
  createDeal,
  getDealById,
  getDealByIdIncludingDeleted,
  listDeals,
  updateDeal,
  softDeleteDeal,
  type Deal,
  type CreateDealInput,
  type UpdateDealInput,
  type ListDealsInput,
} from "./deals";
export {
  createActivity,
  getActivityById,
  listActivities,
  updateActivity,
  softDeleteActivity,
  type Activity,
  type CreateActivityInput,
  type UpdateActivityInput,
  type ListActivitiesInput,
} from "./activities";
export {
  createNote,
  getNoteById,
  listNotes,
  updateNote,
  softDeleteNote,
  type Note,
  type CreateNoteInput,
  type UpdateNoteInput,
  type ListNotesInput,
} from "./notes";
export {
  createTag,
  getTagById,
  listTags,
  updateTag,
  softDeleteTag,
  createTagging,
  listTaggings,
  deleteTagging,
  type Tag,
  type CreateTagInput,
  type UpdateTagInput,
  type ListTagsInput,
  type Tagging,
  type CreateTaggingInput,
  type ListTaggingsInput,
} from "./tags";
export {
  type RelatedToType,
  validateCompanyRelationship,
  validateContactRelationship,
  validateDealRelationship,
  validateRelatedToRelationship,
  validateTagRelationship,
} from "./relationship-validation";
export {
  CrmError,
  ValidationError,
  DuplicateContactEmailError,
  InvalidCompanyRelationshipError,
  InvalidOwnerError,
  InvalidContactRelationshipError,
  InvalidPipelineRelationshipError,
  InvalidStageRelationshipError,
  CannotDeleteDefaultPipelineError,
  InvalidDealRelationshipError,
  InvalidTagRelationshipError,
  DuplicateTagNameError,
  DuplicateTaggingError,
} from "./errors";
export { DEFAULT_LIMIT, MAX_LIMIT, type Page, type Cursor } from "./pagination";
export {
  getDealDashboardMetrics,
  type DealDashboardMetrics,
  type CurrencyAmount,
  type DealsByStageMetric,
} from "./dashboard-metrics";
