import { randomUUID } from "node:crypto";
import { afterAll, describe, expect, it } from "vitest";
import { closePool } from "@ai-revenue-os/database";
import { adminPool, seedAsAdmin, createOrgWithActiveMember } from "./helpers";
import { findProfilesNeedingEmbedding } from "../src/backfill";

process.env.DATABASE_URL ??= "postgresql://postgres:postgres@127.0.0.1:54322/postgres";

afterAll(async () => {
  await adminPool.end();
  await closePool();
});

/**
 * Milestone 4.1 Phase 3 — findProfilesNeedingEmbedding (Detailed Design
 * §O). Identification-only: no vector is ever generated by this function,
 * no external call is ever made — see backfill.ts's own header comment.
 * Bulk-seeds brain_entity_profiles directly (raw SQL), the same "fast
 * bulk seed, bypassing the real projection path" discipline
 * backfill.test.ts's own header comment already establishes for the
 * entity-profile backfill — this test cares about the identification
 * query's own pagination/filter correctness, not projection.
 */
async function seedProfileRow(organizationId: string, computedAt: string): Promise<{ id: string; contactId: string }> {
  return seedAsAdmin(async (client) => {
    const contact = await client.query<{ id: string }>(
      "insert into public.contacts (organization_id, first_name, email) values ($1, 'Bulk', $2) returning id",
      [organizationId, `embed-backfill-${randomUUID()}@example.test`],
    );
    const profile = await client.query<{ id: string }>(
      `insert into public.brain_entity_profiles (organization_id, entity_type, contact_id, profile, computed_at)
       values ($1, 'contact', $2, '{}'::jsonb, $3) returning id`,
      [organizationId, contact.rows[0]!.id, computedAt],
    );
    return { id: profile.rows[0]!.id, contactId: contact.rows[0]!.id };
  });
}

async function seedEmbeddingRow(organizationId: string, entityProfileId: string, sourceVersionAt: string): Promise<void> {
  await seedAsAdmin(async (client) => {
    const vector = `[${Array.from({ length: 1536 }, () => "0").join(",")}]`;
    await client.query(
      `insert into public.brain_embeddings (organization_id, source_type, entity_profile_id, chunk_text, embedding, content_hash, source_version_at)
       values ($1, 'entity_profile', $2, 'x', $3::vector, $4, $5)`,
      [organizationId, entityProfileId, vector, randomUUID(), sourceVersionAt],
    );
  });
}

describe("findProfilesNeedingEmbedding: identification only", () => {
  it("a profile with no embedding row at all is reported as needing embedding", async () => {
    const { organizationId } = await createOrgWithActiveMember();
    const profile = await seedProfileRow(organizationId, "2026-01-01T00:00:00.000Z");

    const [contactReport] = await findProfilesNeedingEmbedding({ organizationId });
    expect(contactReport!.needingEmbedding.map((r) => r.profileId)).toContain(profile.id);
  });

  it("a profile whose embedding is CURRENT (source_version_at >= computed_at) is not reported", async () => {
    const { organizationId } = await createOrgWithActiveMember();
    const profile = await seedProfileRow(organizationId, "2026-01-01T00:00:00.000Z");
    await seedEmbeddingRow(organizationId, profile.id, "2026-01-01T00:00:00.000Z");

    const [contactReport] = await findProfilesNeedingEmbedding({ organizationId });
    expect(contactReport!.needingEmbedding.map((r) => r.profileId)).not.toContain(profile.id);
  });

  it("a profile whose stored embedding is STALE (source_version_at < computed_at, e.g. after a recomputation) is reported again", async () => {
    const { organizationId } = await createOrgWithActiveMember();
    const profile = await seedProfileRow(organizationId, "2026-01-05T00:00:00.000Z");
    await seedEmbeddingRow(organizationId, profile.id, "2026-01-01T00:00:00.000Z"); // older than computed_at

    const [contactReport] = await findProfilesNeedingEmbedding({ organizationId });
    expect(contactReport!.needingEmbedding.map((r) => r.profileId)).toContain(profile.id);
  });
});

describe("findProfilesNeedingEmbedding: multi-page pagination and resume", () => {
  it("scans more than one page (60 profiles, PAGE_SIZE=50) in a single call, reporting all of them", async () => {
    const { organizationId } = await createOrgWithActiveMember();
    const profiles = [];
    for (let i = 0; i < 60; i++) {
      profiles.push(await seedProfileRow(organizationId, "2026-01-01T00:00:00.000Z"));
    }

    const [contactReport] = await findProfilesNeedingEmbedding({ organizationId });
    expect(contactReport!.scanned).toBe(60);
    expect(contactReport!.needingEmbedding).toHaveLength(60);
    expect(contactReport!.cursor).not.toBeNull();
    const reportedIds = new Set(contactReport!.needingEmbedding.map((r) => r.profileId));
    for (const p of profiles) {
      expect(reportedIds.has(p.id)).toBe(true);
    }
  });

  it("resumes from a persisted cursor: a second call after the first only re-scans what's new, not from the start", async () => {
    const { organizationId } = await createOrgWithActiveMember();
    for (let i = 0; i < 55; i++) {
      await seedProfileRow(organizationId, "2026-01-01T00:00:00.000Z");
    }

    const [firstPass] = await findProfilesNeedingEmbedding({ organizationId });
    expect(firstPass!.scanned).toBe(55);

    // Nothing new seeded — a second pass resumes from the persisted
    // cursor (past every already-scanned id) and finds nothing further.
    const [secondPass] = await findProfilesNeedingEmbedding({ organizationId });
    expect(secondPass!.scanned).toBe(0);
    expect(secondPass!.needingEmbedding).toHaveLength(0);
  });

  it("a page containing only already-current profiles still advances the cursor (never stalls forever)", async () => {
    const { organizationId } = await createOrgWithActiveMember();
    const profile = await seedProfileRow(organizationId, "2026-01-01T00:00:00.000Z");
    await seedEmbeddingRow(organizationId, profile.id, "2026-01-01T00:00:00.000Z"); // already current — zero needing-embedding rows in this page

    const [contactReport] = await findProfilesNeedingEmbedding({ organizationId });
    expect(contactReport!.scanned).toBe(1);
    expect(contactReport!.needingEmbedding).toHaveLength(0);
    expect(contactReport!.cursor).not.toBeNull();
  });

  it("idempotent rerun: calling twice in a row with no new data reports zero the second time, never re-reporting the same refs", async () => {
    const { organizationId } = await createOrgWithActiveMember();
    await seedProfileRow(organizationId, "2026-01-01T00:00:00.000Z");
    await seedProfileRow(organizationId, "2026-01-01T00:00:00.000Z");

    const [first] = await findProfilesNeedingEmbedding({ organizationId });
    expect(first!.needingEmbedding).toHaveLength(2);

    const [second] = await findProfilesNeedingEmbedding({ organizationId });
    expect(second!.needingEmbedding).toHaveLength(0);
  });
});

describe("findProfilesNeedingEmbedding: tenant isolation", () => {
  it("never reports another organization's profiles", async () => {
    const orgA = await createOrgWithActiveMember();
    const orgB = await createOrgWithActiveMember();
    await seedProfileRow(orgB.organizationId, "2026-01-01T00:00:00.000Z");

    const [reportA] = await findProfilesNeedingEmbedding({ organizationId: orgA.organizationId });
    expect(reportA!.scanned).toBe(0);
    expect(reportA!.needingEmbedding).toHaveLength(0);
  });
});

describe("findProfilesNeedingEmbedding: precision-safe pagination by construction", () => {
  it("correctly pages/dedupes profiles sharing the EXACT SAME computed_at timestamp — id-keyset pagination has no timestamp-precision dependency at all", async () => {
    const { organizationId } = await createOrgWithActiveMember();
    const sameInstant = "2026-01-01T00:00:00.000000Z";
    const profiles = [];
    for (let i = 0; i < 3; i++) {
      profiles.push(await seedProfileRow(organizationId, sameInstant));
    }

    const [contactReport] = await findProfilesNeedingEmbedding({ organizationId });
    expect(contactReport!.scanned).toBe(3);
    expect(contactReport!.needingEmbedding).toHaveLength(3);
    const reportedIds = new Set(contactReport!.needingEmbedding.map((r) => r.profileId));
    for (const p of profiles) {
      expect(reportedIds.has(p.id)).toBe(true);
    }
  });
});
