// @ts-check
const { FlatCompat } = require("@eslint/eslintrc");
const tseslint = require("@typescript-eslint/eslint-plugin");
const tsParser = require("@typescript-eslint/parser");

const compat = new FlatCompat({ baseDirectory: __dirname });

/**
 * Shared config for apps/web and apps/marketing (Next.js apps).
 * Does not restrict default exports — Next.js App Router requires them
 * for page.tsx/layout.tsx/etc. Route handlers use named exports (GET/POST/...)
 * regardless, so this doesn't weaken the packages/* rule where it matters.
 */
module.exports = [
  ...compat.extends("next/core-web-vitals"),
  {
    files: ["**/*.ts", "**/*.tsx"],
    languageOptions: {
      parser: tsParser,
      parserOptions: {
        project: true,
      },
    },
    plugins: {
      "@typescript-eslint": tseslint,
    },
    rules: {
      ...tseslint.configs.recommended.rules,
      "@typescript-eslint/no-explicit-any": "error",
      "@typescript-eslint/no-unused-vars": ["error", { argsIgnorePattern: "^_" }],
    },
  },
  {
    // next-env.d.ts is regenerated by Next.js on every build/dev run and carries
    // Next's own required triple-slash references — it is never hand-edited, so it
    // is excluded from lint rather than weakening the triple-slash-reference rule
    // for everything else.
    ignores: [".next/**", "node_modules/**", ".turbo/**", "next-env.d.ts"],
  },
];
